Microsoft.PowerPlatform.Tooling.BatchedTelemetry Error: 2 : BatchedSender.SendTransmission Caught unhandled exception while trying to send a transmission.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'westus2-2.in.applicationinsights.azure.com'
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerPlatform.Tooling.BatchedTelemetry.BatchedUpload.BatchedSender.Transmitter.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PowerPlatform.Tooling.BatchedTelemetry.BatchedUpload.BatchedSender.<SendTransmission>d__16.MoveNext()
Microsoft.PowerPlatform.Tooling.BatchedTelemetry Warning: 4 : BatchedSender.SendTransmission returned false after processing transmission file: C:\Users\ANKIT\AppData\Local\Microsoft\PowerAppsCli\telemetry-cache\PluginRegistration\18112-638605232111633987.sending
Microsoft.PowerPlatform.Tooling.BatchedTelemetry Error: 2 : BatchedSender.SendTransmission Caught unhandled exception while trying to send a transmission.
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 20.9.155.150:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PowerPlatform.Tooling.BatchedTelemetry.BatchedUpload.BatchedSender.Transmitter.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PowerPlatform.Tooling.BatchedTelemetry.BatchedUpload.BatchedSender.<SendTransmission>d__16.MoveNext()
Microsoft.PowerPlatform.Tooling.BatchedTelemetry Warning: 4 : BatchedSender.SendTransmission returned false after processing transmission file: C:\Users\ANKIT\AppData\Local\Microsoft\PowerAppsCli\telemetry-cache\PluginRegistration\19024-638605469019508960.sending
